In [4]:
import numpy as np

## 1. arange란?

arange와 range를 같이 보고 이해하시면 됩니다.
(당연히 개념도 매우 직관적이고 쉽습니다)

**[실제 상황 예시]**

우리는 순차적인 값을 생성할 때가 많습니다. 예를 들면 다음과 같습니다.

1. 회원에 대한 가입 번호 부여 (1번 회원부터 순차적으로~)
2. 100개 한정 판매 상품에 대한 고유 번호 부여

등등.. 이 밖에도 데이터 관리를 위한 인덱스를 차례대로 부여하는 것은 매우 흔한 일입니다. (심지어, 엑셀에서도 왼쪽 행에 1번부터~ 쭈욱 부여 되죠?)

### 1-1. 순서대로 리스트에 값을 생성하려면?

1~10까지 값을 생성하려면?

In [2]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### 1-2. arange를 사용해서 쉽게 생성하기

첫번째 인자에는 **start 이상**, 두번째 인자에는 **stop의 미만** 이 들어갑니다.

In [5]:
arr = np.arange(1,11)


In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1-3. keyword 인자를 사용해보기

keyword 인자는 파라미터(인자)의 keyword를 지정해줌으로썬 순서 없이 지정해 줄 수 있습니다.

In [7]:
arr = np.arange(start=1, stop=11)


In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr = np.arange(stop=11, start=1)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 1-4. 홀수의 값만 생성

1~10 사이의 값중 홀수만 생성해 보세요.

**step 키워드 활용**

In [11]:
arr = np.arange(1, 11, 2)


In [12]:
arr

array([1, 3, 5, 7, 9])

In [13]:
arr = np.arange(start=1, stop=11, step=2)


In [14]:
arr

array([1, 3, 5, 7, 9])

## 2. range (numpy와는 상관없는 python 문법)

* range는 말 그대로 범위를 지정해 주는 것입니다.
* np.arange와 헷갈리시는 분들이 많아 이번 시간에 같이 다룹니다.
* 보통 for in 의 반복문에서 많이 사용됩니다.

In [15]:
arr = np.arange(1, 11)


In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10


### 2-1. range 구문 활용시

In [18]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [19]:
for i in range(1, 11, 2):
    print(i)

1
3
5
7
9
